### ISSUE TITLE
SamplesPerPixel value not preserved

### ISSUE THREAD

**Issue by carlkesselman** [glencoesoftware/bioformats2raw#104]
When converting brightfield images. (i.e. .RGB image)  from say CZI, bfconvert  will produce a file with three channels, and a metadata attribute of SamplesPerPixel="3"

When taking the same file and converting with bioformats2raw, the resulting attribute in the METADATA.OME.XML file has a samplesperpixel value of 1.   This makes it very hard to sort out what is actually in the resulting file. 

It would seem that the desired behavior would be to that the metadata from bioformats2raw mirror the metadata produced by bfconvert.

Thanks,

Carl

**Comment by chris-allan** [comment]
Since `bioformats2raw` always produces planar output with a consistent dimension order (TCZYX) [1] and OME-ZARR [2] has no concept of multiple samples per pixel the resultant OME-XML has the correct formulation. We realize this is probably less than ideal for preserving the "RGBness" of the input data and signaling this to downstream tools but it is consistent with the design.

1. https://github.com/glencoesoftware/bioformats2raw/pull/86
2. https://ngff.openmicroscopy.org/latest/

**Comment by carlkesselman** [comment]
Do you have any suggestions as to how I might address this issue.  As it stands I’m using bfconvert to generate OME-XML metadata and using that to identify which channels in the image should be considered RGB.  Otherwise, there is no way to capture this information other than having an external source of this information outside the pipeline, which as you point out, is suboptimal. Having bioformat2raw throw out information that is available in the source file seems suboptimal as well.


----------------------------------------------------------

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute Viterbi School of Engineering Professor,

Professor, Ostrow School of Dentistry
Professor, Preventive Medicine Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  ***@***.***
Web: http://www.isi.edu/~carl
On Jun 23, 2021, 3:54 AM -0700, glencoesoftware/bioformats2raw ***@***.***>, wrote:

OME-ZARR
