### ISSUE TITLE
Delete existing memo files by default?

### ISSUE THREAD

**Issue by melissalinkert** [glencoesoftware/bioformats2raw#136]
If a memo file already exists before the conversion is started, it will be used if it is compatible with the current Bio-Formats version. This can lead to confusion if conversion is being tested with different reader options, since the memo file effectively overrides any options changes.

It might be better to default to deleting the memo file (if it exists) before the first ```setId``` call, and add an option to keep the memo file for the rare cases when that is necessary. ```Memoizer.getMemoFile(String)``` should make that easy.

**Comment by sbesson** [comment]
Another (complementary?) approach would be to delete the memo file at the end of the conversion process.

Since the primary scope of this utility is to perform a one-off conversion and this file is primarily generated for  performance, at least from my side, there is no persistence expectation and it would be completely acceptable to delete it at the end of the process.

**Comment by joshmoore** [comment]
With the caveat that if it exists beforehand, it likely shouldn't be deleted by default afterwards (e.g. in the IDR case)
