### ISSUE TITLE
The term 'bioformats2raw' is not recognized as a name of a cmdlet

### ISSUE THREAD

**Issue by AmmarAmmer** [glencoesoftware/bioformats2raw#163]
I installed python-blosc from (http://python-blosc.blosc.org/install.html). All tests were sucessful:

Doctest: blosc.toplevel.unpack_array ... ok
Ran 39 tests in 4.976s
OK
----------------------------------------------------------------------
I put blosc.dll in the same folder

After that, I set up the path with:

set JAVA_OPTS="-Djna.library.path=C:\python-blosc"

and put blosc.dll in the same folder
----------------------------------------------------------------------
At the last I installed the libraries with:

conda install -c ome bioformats2raw raw2ometiff
----------------------------------------------------------------------
When I use:
bioformats2raw /path/to/file.mrxs  /path/to/zarr-pyramid

I get the message (The term 'bioformats2raw' is not recognized as a name of a cmdlet)

What I'm doing wrong?
Thanks

**Comment by melissalinkert** [comment]
Errors like that usually mean that the `PATH` environment variable doesn't include the folder where `bioformats2raw.bat` and `raw2ometiff.bat` are installed. If you are not running `bioformats2raw` from an Anaconda Prompt, either add the correct folder to the `PATH` environment variable, or specify the full path to `bioformats2raw.bat` instead of just `bioformats2raw`. You might also try running `bioformats2raw` from an Anaconda Prompt instead of PowerShell.

If that doesn't help, https://github.com/ome/conda-bioformats2raw is the better place to ask questions about the Conda package. The OME team maintains that package separately from bioformats2raw itself.

Closing here since I can't transfer the issue to https://github.com/ome/conda-bioformats2raw.
