### ISSUE TITLE
Colors per channel are not the same than original .mrxs file

### ISSUE THREAD

**Issue by ltalignani** [glencoesoftware/bioformats2raw#204]
Dear all,

I am using bioformats2raw and raw2ometiff (latest versions installed with conda) to convert fluorescence image, coming from a 3Dhistech slides scanner, in .mrxs format. 

`bioformats2raw --progress lame1.mrxs zarr-pyramid-lame1/ `

followed by 

`raw2ometiff zarr-pyramid-lame1/  pyramid.lame1.ome.tiff `

When I try to open the ome.tiff generated in Qpath, the channel colors are inverted 

Image opened by QPath:

<img width="849" alt="Capture d’écran 2023-05-26 à 21 32 44" src="https://github.com/glencoesoftware/bioformats2raw/assets/53080888/e542bf5c-eb3f-45e8-82a2-9117041401d3">

Original slide, in .mrxs format:
![Capture d’écran 2023-05-26 213420](https://github.com/glencoesoftware/bioformats2raw/assets/53080888/ec3e73f9-4d2c-4541-ba7d-b863be78c8bd)

Is there a flag that can manage color per channel?

Thanks for your help

**Comment by melissalinkert** [comment]
Thanks for reporting this, @ltalignani. By latest versions, do you mean bioformats2raw 0.6.1 and raw2ometiff 0.4.1?

There isn't a flag to control which colors are assigned to which channels - that information is supposed to be automatically detected from the `Slidedat.ini` file in the .mrxs dataset. From the screenshots, it's difficult to tell if this is a problem with the channel colors being set incorrectly, or a problem of the channels themselves being out of order. We would need to see the original dataset that demonstrates this problem in order to investigate.

**Comment by ltalignani** [comment]
Thanks @melissalinkert for your answer. 

I have the following information:
Bioformats2raw Version = 0.6.1
Bio-Formats version = 6.12.0
NGFF specification version = 0.4

Raw2ometiff Version = 0.4.1.

And you can download the .marxs files at this address:

https://filesender.renater.fr/?s=download&token=d4b7321c-eece-4f9e-939c-35e3e8f464d4

Sorry, the .dat files are not in a specific directory. You have to create it. 

Thanks a lot

**Comment by melissalinkert** [comment]
> And you can download the .marxs files at this address:
>
> https://filesender.renater.fr/?s=download&token=d4b7321c-eece-4f9e-939c-35e3e8f464d4

Unfortunately, I see an error message when trying to access the data:

![image](https://github.com/glencoesoftware/bioformats2raw/assets/109998/3e04b22a-594e-46f1-b8a0-80b59c1953b9)

Could you please check the link, or upload to https://zenodo.org/ instead?

**Comment by melissalinkert** [comment]
As noted above, I strongly suspect there is a little more to the issue than just incorrect colors. We'll definitely need to see the data in order to investigate further, though.

In the absence of a working download link, closing for now. @ltalignani, if you're able to upload the dataset somewhere else, let us know the new link and this issue can be re-opened.
