### ISSUE TITLE
Docker containers for new releases

### ISSUE THREAD

**Issue by krokicki** [glencoesoftware/bioformats2raw#243]
It looks like the latest Docker container is [openmicroscopy/bioformats2raw:0.5.0](https://hub.docker.com/layers/openmicroscopy/bioformats2raw/0.5.0/images/sha256-1ed9b56f133bdb89142d01f5c1e1d430d41aab63b29f6274b6b0c207c674ec77?context=explore) from over a year ago. Would it be possible to publish new releases as Docker containers? That would help enable usage of this software, e.g. in a Nextflow pipeline: https://github.com/BioinfoTongLI/to_ome_tif

**Comment by sbesson** [comment]
Thanks @krokicki, this Docker image was developed by OME rather than Glencoe Software. At present, we have currently no plan to build & support Docker images for each bioformats2raw release.
Closing this issue as I cannot transfer issues across organizations. As indicated by @jburel above, https://github.com/ome/bioformats2raw-docker is the repository containing the source of the Docker image and where this discussion should probably take place.

**Comment by jburel** [comment]
@krokicki A new version of the docker container is now available. It contains version 0.9.1 of bioformats2raw.

**Comment by krokicki** [comment]
Thanks so much, @jburel!
