### ISSUE TITLE
RFE: Chunk size setting

### ISSUE THREAD

**Issue by joshmoore** [glencoesoftware/bioformats2raw#72]
During I2K, it was requested to permit setting the ZTC chunk-sizes from the CLI. Talking it through with attendees, it was unclear to me if the current algorithm has any assumptions about the current default chunk size. If a different chunk size would be suboptimal for the writing process, I'm inclined to say that a second pass with https://github.com/pangeo-data/rechunker/ might be a reasonable workaround.

**Comment by melissalinkert** [comment]
Maybe I misunderstand the question, but using ```-w``` and ```-h``` should already allow the XY chunk size to be changed: https://github.com/glencoesoftware/bioformats2raw/blob/master/src/main/java/com/glencoesoftware/bioformats2raw/Converter.java#L818

The remaining dimensions are definitely assumed to have a chunk size of 1.  I don't think it would be a problem to make that configurable (and update raw2ometiff to handle that case), but it hasn't been a priority since most of the original use cases here were single Z/T.

**Comment by joshmoore** [comment]
Sorry, updated the description to say "ZTC chunk-sizes".

**Comment by joshmoore** [comment]
First step of this is in https://github.com/glencoesoftware/bioformats2raw/pull/81
